# .woodpecker.yml
pipeline:
  build:
    image: debian
    commands:
      - echo "This is the build step"
      - ls -la
  a-test-step:
    image: debian
    commands:
      - echo "Testing.."
      - ls -la
      - cat ./bin/kconfig-hardened-check
