# .woodpecker.yml
steps:
  unit-test:
    image: python:3
    pull: true
    commands:
      - echo "Prepare the engine unit-test..."
      - python --version
      - pip install --no-cache-dir coverage
      - echo "Run unit-tests and collect coverage..."
      - coverage run --include=kconfig_hardened_check/engine.py,kconfig_hardened_check/test_engine.py -m unittest -v -b
      - echo "Show the coverage report..."
      - coverage report
